### ISSUE TITLE
Use Kotlin DSL for Kotlin examples

### ISSUE THREAD

**Issue by kensiprell** [micronaut-projects/micronaut-predator#11]
I have a working `build.gradle.kts` written in Kotlin DSL for example-jdbc-kotlin. If you like, I can submit it in a PR.

Of course, if we switch from Groovy to Kotlin for this example, we should probably do it for all Kotlin examples across the Micronaut ecosystem. If you're interested in changing them, I can take a look at the others  and probably submit PRs for those as well.

**Comment by kensiprell** [comment]
See this branch: https://github.com/kensiprell/micronaut-predator/blob/kotlin-dsl/examples/example-jdbc-kotlin/build.gradle.kts

**Comment by graemerocher** [comment]
Sounds great. PRs welcome
