### ISSUE TITLE
Join Queries & lazy

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-predator#15]
In the Join Queries example https://micronaut-projects.github.io/micronaut-predator/snapshot/guide/#joinQueries
```
@Entity
data class Product(
    @Id
    @GeneratedValue
    var id: Long?,
    var name: String,
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    var manufacturer: Manufacturer
)
```
What means ` fetch = FetchType.LAZY` in this example? The field `manufacturer` is not optional, how it could be lazy?

**Comment by graemerocher** [comment]
It actually means nothing and should be removed from the example. Lazy fetching is not supported
