### ISSUE TITLE
Conditional queries

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-predator#16]
```
@Entity
data class Product(
    @Id
    @GeneratedValue
    var id: Long?,
    var name: String,
    @ManyToOne(optional = false, fetch = FetchType.LAZY)
    var manufacturer: Manufacturer
)

@Entity
data class Manufacturer(
    @Id
    @GeneratedValue
    var id: Long?,
    var name: String
)
```
User may want to search the products by manufacturer name, in this case we need to join `manufacturer` and to add restriction to criteria, but in case it user do not search by manufacturer name, than we do not need to join and to add restriction.
So, how to handle conditional queries?

**Comment by franz-see** [comment]
@raderio I believe conditional queries can be done by implementing your Predator Repository as an abstract class instead of an interface. 

https://micronaut-projects.github.io/micronaut-predator/snapshot/guide/#repositories

**Comment by graemerocher** [comment]
Indeed abstract classes methods or the layer that invokes the repository is where you would do this
