### ISSUE TITLE
Question: DTO Projections how it knows about entity table

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-predator#18]
https://micronaut-projects.github.io/micronaut-predator/snapshot/guide/#dto
Can you please add some more description into documentation, it is not clear how 
```
fun findOne(title: String): BookDTO
```
knows that it should extract data from book table?
How it will be if I need multiple dto projection to same entity/table?

**Comment by franz-see** [comment]
@raderio It knows via the Repository interface that that method belongs to, and then the mapping is as is table column to object property. So as long as the column names can be mapped into the DTO, you can have multiple DTOs for the same table/Entity.

> The DTO should include properties that match the property names you wish to project on (in this case title and pages). If any properties do not match then a compilation error will occur.

**Comment by raderio** [comment]
Very nice. Thank you.
