### ISSUE TITLE
Query Method Pattern

### ISSUE THREAD

**Issue by raderio** [micronaut-projects/micronaut-predator#22]
At he moment query patterns are written in the method name. 
I think it will be better to write patterns in parameters name.
Instead of
```
findByTitleStartsWith(String title)
```
we always can use a more general `find` or `findBy` method name
```
findBy(String titleStartsWith)
findBy(String title)
```
In this case no need to repeat `title` in method name and for parameter.

Also we can add some annotations to the parameters, something like
```
findBy(@Pattern(StartsWith) String title)
```

**Comment by graemerocher** [comment]
Whilst I understand the suggestion we had considered this and there are a couple of reasons why we won't be doing this:

1. GORM and Spring Data compatibility was a priority and the pattern matches those implementations making it easier for users to migrate
2. Using the parameter name does mean that you always have to pass `-parameters` to the compiler which is not always the case (see for example when compiling Spring Data compliant interfaces)

**Comment by raderio** [comment]
Maybe this can be added as separated option, for example if method is called `findBy` than patterns can be in parameters name.
Another point why is it better is that method name can not be splitted in multiple lines, but parameters we can put each on new line.

**Comment by raderio** [comment]
https://github.com/micronaut-projects/micronaut-data/issues/89

**Comment by raderio** [comment]
>Using the parameter name does mean that you always have to pass -parameters to the compiler 

This also can be solved by annotations, just like `@RequestParam` in Spring.
